# Generated by Django 2.2.2 on 2019-06-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table1',
            new_name='test',
        ),
    ]
